version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pawnshop-db
    environment:
      POSTGRES_DB: pawnshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - DB_URL=jdbc:postgresql://postgres:5432/pawnshop
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgrespassword
      - JAVA_OPTS=-Xmx350m